version: '3.7'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 1924:1924
    links:
      - nodeapp_1
      - nodeapp_2
  nodeapp_1:
    image: nodeapp:${VERSION}
    container_name: nodeapp_1
    environment:
      SERVICE_NAME: nodeapp_1
    env_file:
      - nodeapp/.env
    depends_on:
      - jaeger
    links:
      - jaeger
  nodeapp_2:
    image: nodeapp:${VERSION}
    container_name: nodeapp_2
    environment:
      SERVICE_NAME: nodeapp_2
    env_file:
      - nodeapp/.env
    depends_on:
      - jaeger
    links:
      - jaeger
      - nodeapp_1
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"


